DataDog/omnibus-software

config/software/boto.rb, config/software/curl.rb, config/software/kafka-python.rb, config/software/paramiko.rb, config/software/pip.rb, config/software/psycopg2.rb, config/software/pycurl.rb, config/software/pymongo.rb, config/software/pymysql.rb, config/software/pyro4.rb, config/software/requests.rb, config/software/simplejson.rb, config/software/snakebite.rb, config/software/supervisor.rb, config/software/sysstat.rb, config/software/util-macros.rb, config/software/xproto.rb
Those “should be safe” to update.
It will require a bit of testing though
=> Update a few dependencies

config/software/python.rb
Changelog:
https://hg.python.org/cpython/raw-file/15c95b7d81dc/Misc/NEWS
=> Update to python 2.7.10

config/software/ntplib.rb
The project's owners decided to do so today so we followed... even
better, they made a new release just for that :)
=> [ntplib] Updated license to MIT License

config/software/psutil.rb
Related to https://github.com/DataDog/dd-agent/pull/2134
=> [psutil] Upgrade to v3.3.0

config/software/datadog-gohai.rb
Related to https://github.com/DataDog/gohai/pull/19
=> [gohai][windows] Pass version to go build command

config/software/datadog-gohai.rb
Related to https://github.com/DataDog/gohai/pull/19
=> [gohai] Pass version to go build command

config/software/python-consul.rb, config/software/python-etcd.rb
Related to https://github.com/DataDog/dd-agent/pull/2008 and https://github.com/DataDog/dd-agent-omnibus/pull/55
=> [Service discovery] Add python-etcd and python-consul as dependencies

config/software/datadog-gohai.rb
Related to https://github.com/DataDog/gohai/pull/30
=> [gohai] Add seelog dep

config/patches/python/python-2.7.11-fix-platform-ubuntu.diff, config/software/python.rb
Fix https://github.com/DataDog/dd-agent/issues/2338
Patch coming from https://bugs.python.org/file18389/use-lsb-release-first.diff
=> [python] Patch to improve distribution detection on ubuntu

config/software/python.rb
And use a sha-2 sum while we're at it
Changelog: https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS
=> [python] Upgrade to 2.7.12

.gitignore, .travis.yml, Gemfile, README.md, Rakefile, config/software/chef.rb, config/software/go.rb, config/software/libyaml-windows.rb, config/software/nagios.rb, config/software/openssl-windows.rb, config/software/ruby-windows-devkit-bash.rb, lib/omnibus-software.rb, lib/omnibus-software/version.rb, omnibus-software.gemspec
Added a `rake` task to build a software along with its dependencies.
Avoid creating a fake project with given dependencies, just clone this repo, make changes, build to see they work.
* I had to merge some stuff from upstream, my changes were added so that further pulls should be smooth
* Tests are failing because they have to, we need to address failures at some point
=> [Rakefile] Provide build task to try softwares without building a project

config/software/curl.rb
See https://curl.haxx.se/changes.html#7_51_0
cc: @olivielpeau
=> [curl] upgrade to 7.51.0

config/software/cacerts.rb
=> [cacerts] update

config/software/setuptools.rb
Instead of using a script, let's use the same install method as Unix.
=> [setuptools] pin version on Windows

config/software/datadog-gohai.rb
This reverts commit 5eea1a78378bb270bb4b9d22dd070d4bfb3037b1.
=> Revert "[gohai] use glide for dependency management"

config/software/datadog-upgrade-helper.rb
The windows installer requires a new upgrade helper application.  This change provides the description for building that application.
=> Adds definition for new upgrade helper application

config/software/python-redis.rb
So that it's up-to-date with integrations-core and dd-agent's
`requirements.txt`
=> [python-redis] Bump bugfix version

config/software/pyasn1.rb, config/software/pysnmp.rb
Adding subdepency to omnibus, ensuring it's pinned to `0.1.9`
=> [pysnmp] adding pyasn1 subdependency.

config/software/curl.rb, config/software/py2app.rb, config/software/qt.rb
Mac build was not working, this is the minimum amount of fixes which allows us to build a Mac agent.
=> [mac] fixes to build the agent

config/software/requests.rb
There are some issues with the current version (see https://github.com/kennethreitz/requests/issues/2568 for instance), and it's an old version anyway so let's update it to the latest
See Datadog/dd-agent#3222 for change on dd-agent
=> [requests] Upgrade to latest (2.13.0)

config/software/py-compiled-cleanup.rb
Can be shared between projects, so it makes sense to have it here.
=> [py-compiled-cleanup] Add software def

config/software/net-snmp-lib.rb, config/software/net-snmp-slim.rb, config/software/net-snmp.rb
Need this to build agent 6 with the SNMP check. Could have some windows collateral.
=> [net-snmp] adding software definition

config/software/rancher-metadata.rb
Adding dependency in support of this dd-agent PR: https://github.com/DataDog/dd-agent/pull/3366
=> [core] Adding rancher-metadata-python dependency

config/software/docker-py.rb
This bug is currently breaking the macOS build
=> [docker-py] Fix install scripts dir sep

.travis.yml, config/software/jmxfetch.rb
Add version 0.15.0 of JMX fetch
=> Add version 0.15.0 of jmxfetch

config/software/nfsiostat.rb
This is needed for the nfsiostat Pull Request: https://github.com/DataDog/integrations-core/pull/720
This is also required for https://github.com/DataDog/dd-agent-omnibus/pull/196
=> adds nfsiostat

config/software/protobuf-py.rb
If the RHEL version works just fine, we're in for a bit of cleanup
=> [protobuf] bump version

config/software/protobuf-py.rb
forgot updating the artifact hash!
=> [protobuf] update hash

config/software/prometheus-client.rb
Add a Python requirement for [prometheus-client](https://github.com/prometheus/client_python)
=> software: add prometheus client python requirement

config/software/cacerts.rb
--------------------------------------------------
=> update cacerts recipe to create both cacert.pem and cert.pem on windows

config/software/jmxfetch.rb
Bump JMXFetch definition to 0.19.0
Was a software definition added? Or a new version to an existing definition?
--------------------------------------------------
=> bump jmxfetch version

config/software/requests.rb
This PR upgrades requests to 2.18.4, the version we use everywhere else
=> upgrade requests

config/software/jmxfetch.rb
https://dd-jmxfetch.s3.amazonaws.com/jmxfetch-0.20.0-jar-with-dependencies.jar
=> [jmxfetch] update to 0.20.0

config/software/curl.rb
=> upgrade curl

config/software/cacerts.rb
`curl https://curl.haxx.se/ca/cacert.pem | sha256sum`
=> update cacert hash

config/software/python.rb
=> Bump python version to 2.7.15

config/software/bzip2.rb
bzip.org is dead / they forgot to renew their domain
=> download bzip2 from one of our buckets

config/software/datadog-metro.rb
This should have been added in https://github.com/DataDog/omnibus-software/pull/202
=> fix gometro on rhel

config/software/datadog-metro.rb
sister PR: https://github.com/DataDog/dd-agent-omnibus/pull/274
=> [datadog-metro] binary will be launched by wrapper script

config/software/datadog-pip.rb
@DataDog/agent-core @DataDog/agent-integrations Can we please review and merge this ASAP to update pip for Agent 6.6? It looks like missed this earlier...
=> update pip-10.0.1+TUF to pip-18.1+TUF+in-toto

config/software/distro.rb
see https://github.com/DataDog/dd-agent/pull/3794
=> Add distro software definition

config/software/requests.rb
Bump `requests` version to 2.20.1
=> Bump requests version to 2.20.1

config/software/kazoo.rb
To match https://github.com/DataDog/integrations-core/pull/2766
=> Bump Kazoo to 2.6.0

config/software/cacerts.rb
=> Fix cacerts sha256 signature.  Update Wed Jan 23 04:12:09 2019 GMT

config/software/psutil.rb
To reflect change in integrations-core: https://github.com/DataDog/integrations-core/pull/3019 (and earlier upgrades that were missed here)
=> [psutil] Upgrade to 5.5.0

config/software/pip.rb
same version as the one our custom pip was based on
=> Upgrade to pip 18.1

config/software/requests.rb, config/software/six.rb
See:
https://github.com/DataDog/integrations-core/pull/3276
https://github.com/DataDog/integrations-core/pull/3274
https://github.com/DataDog/integrations-core/pull/3272
=> Upgrade six & requests

.travis.yml
https://github.com/DataDog/integrations-core/blob/e3b1d64dfb1f40ec8e0b311752960ebd488387dd/.travis.yml#L19-L21
=> Don't trigger multiple CI jobs for pull requests

config/software/datadog-agent-six.rb, config/software/python3.rb
=> Add software definition for Six

config/software/python.rb
=> Bump Python version to 2.7.16

config/software/curl.rb, config/software/pycurl.rb
Built new pycurl wheel with updated libcurl.
=> change to new custom pycurl

config/software/cacerts.rb, config/software/cacerts_py2.rb, config/software/cacerts_py3.rb
- Update checksum
- Pin a specific version, so another update doesn't break the builds
=> Fix cacerts checksum missmatch

config/software/jmxfetch.rb
=> [jmxfetch] Bump to 0.26.2

config/software/cacerts_py2.rb, config/software/cacerts_py3.rb
Updates latest cert hash for newly generated certificate
=> Update to latest cert hash

config/software/curl.rb, config/software/pycurl.rb
Use the latest version of curl and pycurl.
=> Bump curl version

config/software/cacerts.rb
Same as for the Windows definitions: #327
=> Update cacerts checksum

config/software/cacerts.rb
=> Update cacerts hashsum 

config/software/cacerts.rb
=> Fix typo incacerts

Gemfile
=> Use the agent-v5 branch of omnibus-ruby in Gemfile

config/software/jmxfetch.rb
As the title states, bump jmxfetch and cleanup.
=> [A5][jmxfetch] bump to latest version + cleanup old shas

config/software/cacerts.rb
=> [cacerts] Update hash (2021-05-25)

config/software/cacerts.rb
=> [backport] [cacerts] 2022-10-11 update

config/software/zlib.rb
https://github.com/madler/zlib/releases/tag/v1.2.13
Test agent build pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/10497566
=> [zlib] Upgrade to 1.2.13

config/software/zlib.rb
=> [7.40.x backport] [zlib] Upgrade to 1.2.13

config/software/cacerts.rb
Regular certificate update
Monitoring alert
=> Update CA certificate

config/software/nfsiostat.rb
This PR backports #457 to `7.45.x`.
=> Change nfsiostat source to url to ensure it is cached

config/software/nfsiostat.rb
This PR backports #457 to `7.46.x`.
=>  Change nfsiostat source to url to ensure it is cached

config/software/unixodbc.rb
See the code comment for details.
=> Make unixodbc depend on postgresql to fix postgresql build

config/software/cacerts.rb
Update CA cert to fix monitor alert
=> Update CA cert with new version 2023-08-22

config/software/ncurses.rb
Tested with this pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/20254584
=> ncurses: disable man pages, tests and programs

config/software/curl.rb
curl published a new version to fix security issues, so we update to this version
[Discussion](https://github.com/curl/curl/discussions/12026) from curl project.
Test [pipeline](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/21432425) (see build [job](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/346868818))
```
[NetFetcher: curl] I | 2023-10-11T07:06:30+00:00 | Extracting `/omnibus/cache/curl-curl-8.4.0.tar.gz' to `/omnibus/src/curl'
```
=> Update curl to latest version

.gitlab-ci.yml
This will simplify testing our omnibus changes. https://datadoghq.atlassian.net/browse/APL-1767
This requires https://github.com/DataDog/datadog-agent/pull/20605 to be merged in order to provide the omnibus branch through the environment
=> Run datadog-agent pipeline on branch push

.gitlab-ci.yml
Seems like one extra paste was performed :')
=> CI: fix default branch rule

config/software/nghttp2.rb
Cherry pick https://github.com/DataDog/omnibus-software/commit/b0fe66bb559b72f98256cc34d12007b8db1218b2
=> [VULNOPS-1127] [Backport #496] Upgrade nghttp2

.github/labeler.yml, .github/workflows/no-auto-bump.yml, .github/workflows/open-datadog-agent-pr.yml, lib/omnibus-software.rb
Or simply when the label was manually set
=> Don't create auto bump PR when a PR contains no actual code change

config/software/libxml2.rb
=> Bump libxml2

.github/workflows/open-datadog-agent-pr.yml
No need to run it if we are on release branches because the PR is always opened on main in the Agent
=> Open a PR in the Agent only on merges on master

config/software/curl.rb
=> Update cURL to 8.7.1

config/software/curl.rb
Disable documentation, versioned symbols & code generation
=> curl: disable some unneeded features

config/software/openssl3.rb
=> [BARX-823] Bump openssl to 3.3.3
