- config/software/cacerts.rb
New version to the certificate at http://curl.haxx.se/ca/cacert.pem
> New cacert version with updated md5.

- config/software/qt.rb
Pin homebrew version so that a previous version of the qt bottle is
installed. Current versions cause an issue with the openssl libraries.
This is a temporary fix, in the long term we should try to get rid of the Qt dependency.
> [osx][qt] Fix openssl issue

- config/software/openssl.rb
The version of OpenSSL that currently runs on our build containers
(~0.9.8) fails to complete the SSL handshake with www.openssl.org, so
let's keep using plain HTTP.
Fixes the builds.
> [openssl] Download source through plain HTTP

- config/software/cacerts.rb
- config/software/curl.rb
http://curl.haxx.se now redirects to https://... , and the https
website requires TLS, which is not compatible with the openssl version
that we run on our CentOS 5-based containers (and that ruby uses).
Switch to our s3 bucket as a temp workaround until we update openssl
and link ruby against it on our container image.
> [curl][cacerts] Use our s3 bucket instead of the curl website

- config/software/openssl.rb
We should do this for every software def now that we use omnibus5, which supports sha2 sums.
> [openssl] Use sha2 sum

- config/patches/python/python-2.7.11-avoid-allocating-thunks-in-ctypes.patch
- config/software/python.rb
On SELinux-enabled environments, an import of the `ctypes` module
raises a `MemoryError` and a subsequent segfault. To avoid this we
remove the faulty line that seem to have been there only for windows
64 bit.
A similar patch is present on some packaged Python versions provided
on some distros, see for instance on the Fedora python 2.7.3-4 pkg:
https://lists.fedoraproject.org/pipermail/scm-commits/2012-April/772613.html
This issue has shown up in the `5.7.0` Datadog Agent because of the newly-included `uptime` module that imports `ctypes` without catching `MemoryError`s (see https://github.com/Cairnarvon/uptime/blob/2f2e4f945182449c9589675c35b2d41060b09fbe/src/__init__.py#L16).
Should fix https://github.com/DataDog/dd-agent/issues/2327
> [python] Patch ctypes to avoid import failure on SELinux

- config/software/datadogpy.rb
Previously pip was set to ignore the packages that were already
installed, which led pip to install `requests` (one of datadogpy's
deps) with a different version than the one specified in `requests`'
software def.
To fix this, make pip consider already-installed packages.
> [datadogpy][requests] Do not re-install `requests` with `datadogpy`

- config/software/datadog-gohai.rb
- config/software/datadog-metro.rb
(comes with another commit that fixes the name of the 3rd party license file for go-metro)
> Add gopsutil dependency for gohai's processes collector

- config/software/boto.rb
There is a bug in boto 2.36.0 that is fixed in the 2.39.0 release: boto/boto#3399
> [dependencies] Upgrade boto 2.36.0 -> 2.39.0

- config/software/pyyaml.rb
pyyaml.org has DNS resolution issues. Use a copy of the license hosted
on our s3 bucket instead.
> [pyyaml][license] Use our s3 bucket instead of pyyaml.org

- config/software/libyaml.rb
pyyaml.org is down, host the src pkg on our s3 bucket instead
> [libyaml] Host on our s3 bucket

- config/software/scandir.rb
Scandir provides us with much faster directory walking, and is now
folded into Python 3.5 as part of the standard lib. It avoids an
extraneous stat() on each file as the directory is walked.
More information can be found here: https://github.com/benhoyt/scandir#background
> [core][directory] Add scandir dependency

- config/software/datadog-gohai.rb
Using `go get -u` on gohai checkouts the master branch of gopsutil.
To pin it properly, checkout version `v2.0.0` of gopsutil after
`go get`ting gohai.
> [gohai] Properly pin gopsutil version

- config/software/openssl.rb
The http URL now redirects to https, and the https endpoint uses a
version of SSL that's not compatible with the openssl client shipped with debian 6.
To fix this, use ftp until we upgrade our build images to debian 7
> [openssl] DL source through ftp

- config/software/libyaml.rb
So that we don't have to update the software definition every time
there is a new commit on the master branch of libyaml.
> [libyaml] Pin libyaml version to the current tip

- config/software/docker-py.rb
Docker recently introduced networks, docker-py 1.3.1 doesn't support them, let's upgrade to the most recent version.
tested successfully
related: https://github.com/DataDog/dd-agent/pull/2556
> Bump docker-py to 1.8.1 for network features

- config/software/kafka-python.rb
Reverts DataDog/omnibus-software#66
Let's revert the upgrade until the `kafka_consumer` check is changed accordingly (see https://github.com/DataDog/dd-agent/pull/2709)
> Revert "Upgrade kafka-python to 1.2.5"

- config/software/kafka-python.rb
Version bump for kafka. See https://github.com/DataDog/dd-agent/pull/2709.
> [kafka-python] bumping lib version to 1.2.5.

- config/software/python-etcd.rb
- config/software/requests.rb
The RSS of the agent processes increased by  ~5MB per python process because of an upgrade of `urllib3` to `1.17`.
1. Pin `urllib3` to `1.16`
The nightly Agent recently picked up version `1.17` of `urllib3` (dep of `python-etcd`), which introduces changes to its deps and the way it loads its deps for its pyopenssl contrib module (see https://github.com/shazow/urllib3/pull/930) . Unfortunately these changes cause a lot of new imports (`OpenSSL`, `idna`, `cryptography`) which lead to the RSS increases of the python processes. AFAIK we do not need the changes brought by the `1.17` upgrade in `python-etcd`, so let's pin `urllib3` to `1.16`.
NB: the `urllib3` module is loaded in all of the Agent's processes because of some service-discovery-related modules (`config.py` imports stuff from …
> Pin to `urllib` to `1.16` + upgrade `requests` to `2.6.2`

- config/software/libffi.rb
- config/software/procps-ng.rb
This is a fix that's already been added to the chef upstream branch, this backport will allow us to build SUSE Enterprise packages.
> SUSE Enterprise

- Gemfile
That's the branch we use by default everywhere else
> [ci] Use `datadog-5.5.0` branch of `omnibus-ruby` in CI/dev envs

- config/software/python.rb
This is a change I've wanted to make for a while, and figured this was the best time to do it.
Python is currently compiled with O3. Most OS's compile it with O2. There's no reason to optimize more than any of the OS's we're targeting.
There's a bunch of reasons why they use O2 instead of O3. First, O3 is slightly buggier than O2. I don't think it's caused any bugs in our code, however it makes it harder to track down intransigent bugs because they could be caused by the compiler optimization. Additionally, because it's biggest feature is the inlining of functions, it means that the package itself will be larger. It also ensure that we will have higher memory usage (something we should avoid).
I don't think that we need the additional optimizations, especially when they can introduce bugs …
> compiles python with O2 rather than O3

- config/software/pip.rb
- config/software/pyro4.rb
- config/software/setuptools.rb
Also requires bump on pyro4 version and setuptools.
Supersedes #60
Motivation:
> Allows users to install wheels on Windows more easily.
Note: Builds w/o errors on deb-x64
> [pip] Upgrade to 8.1.2

- config/software/python.rb
See https://hg.python.org/cpython/raw-file/v2.7.13/Misc/NEWS
Build works on `deb-x64`
Haven't checked that the windows build still works (I've updated the shasum for windows though), pinging @degemer and @derekwbrown :)
> [python] Upgrade to `2.7.13`

- config/software/kafka-python.rb
There's a number of bug fixes and issues since the 1.2.5 release.
Details in https://github.com/DataDog/dd-agent/pull/2863
> Bump kafka-python to 1.3.1

- config/software/boto.rb
- config/software/pywin32.rb
pywin32: use `--prefix` option instead of the equivalent
`--install-option="--prefix='/blabla'"`, which can be used with wheels
and does not require a full rebuild of the lib.
boto: remove the --install-scripts option (doesn't work anymore). We
seem to be only importing boto, not using its command line utility.
> [windows] fix definitions broken by pip 8.1.2

- config/software/cacerts.rb
Based on the chef upstream software def. I'd be surprised if the def we currently use ever worked properly, but it surely doesn't now.
Creates the cert file in `/opt/datadog-agent/embedded/ssl/certs/cacert.pem` and (on unix) a symlink to it in `/opt/datadog-agent/embedded/ssl/cert.pem`.
We choose to always pull the latest version instead of pinning one to
force us to always keep the certs up-to-date.
> [cacerts] Fix software def

- config/software/docker-py.rb
This is needed to follow the required version in the testing env.
Ref: https://github.com/DataDog/dd-agent/pull/3108
> Upgrade docker-py version to 1.10.6

- config/software/guidata.rb
Guidata was hosted on Google Code, which is now dead for real.
This commit switches the source to Github. The md5 changes because the
previous zip was slightly compressed (and was not shipping the tests for
instance), whereas this one contains the entire source code (because
it's automcatically generated by Github).
> [guidata] new source

- config/software/flex.rb
For some SSL-related reason our deb image can't download from the
previous url.
> [flex] Pull from sourceforge

- config/software/datadog-gohai.rb
- config/software/datadog-metro.rb
Use it for datadog-metro and datadog-gohai.
Also complete change of the gohai build process, because we now use `glide` for Go dep management. This only works when using the `master` branch of gohai for now, b/c the glide changes are not yet on `last-stable`.
> Return of always_build option

- config/software/pysnmp-mibs.rb
- config/software/pysnmp.rb
Break the existing circular dependency (omnibus-to-pip-to-omnibus) revolving around pysnmp. This was creating inconsistencies.
> [pysnmp] break omnibus-pip circular dependency.

- config/software/cryptography.rb
```
Metadata-Version: 1.1
Name: cryptography
Version: 1.7.2
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /opt/datadog-agent/embedded/lib/python2.7/site-packages
Requires: idna, pyasn1, six, setuptools, enum34, ipaddress, cffi
Entry-points:
[cryptography.backends]
openssl = cryptography.hazmat.backends.openssl:backend
```
It's bringing in `pyasn1` as well, sorry I missed this one too.
> [cryptography] depends on pyasn1.

- config/software/cryptography.rb
- config/software/pyopenssl.rb
```
Metadata-Version: 1.1
Name: pyOpenSSL
Version: 0.14
Summary: Python wrapper module around the OpenSSL library
Home-page: https://github.com/pyca/pyopenssl
Author: Jean-Paul Calderone
Author-email: exarkun@twistedmatrix.com
License: APL2
Location: /opt/datadog-agent/embedded/lib/python2.7/site-packages
Requires: cryptography, six
```
```
Metadata-Version: 1.1
Name: cryptography
Version: 1.7.2
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /opt/datadog-agent/embedded/lib/python2.7/site-packages
Requires: idna, pyasn1, six, setuptools, enum34, …
```
> [cryptography] dependency missing in branch.

- config/software/pysnmp.rb
- config/software/tornado.rb
- config/software/uptime.rb
- config/software/uuid.rb
- config/software/virtualenv.rb
- config/software/virtualenvwrapper.rb
Switch would ignore already installed deps, potentially upgrading certain packages. This broke `pysnmp`, for instance, by dragging along a new version of `pyasn1`. 
This should address that, and other potential dependency issues.
> [pip] remove -I switch from all calls.

- config/software/tornado.rb
- config/software/uptime.rb
- config/software/uuid.rb
Removing three more `-I` switches to ensure we keep the build dependencies under control.
> [pip] remove more -I lingering switches.

- config/software/datadog-gohai.rb
https://github.com/DataDog/gohai/pull/39, which changes gohai from running
wmic commands
> [Windows] add registry as a dependency for gohai checks.  Required for

- config/software/requests.rb
For some reason `requests` v2.12.0 to 2.13.0 use ~10MB more memory
once they're imported, which totals 30MB for the 3 main agent processes
and that's not acceptable
> [requests] Downgrade to `2.11.1`

- config/software/vc_redist.rb
Update the runtime zip with the manifest.
Load the DLLS in both dist and embedded, or the various executables (ddagent.exe, python.exe, etc.) won't run.
> Update runtime zip with manifest file so that it will load

- config/patches/python/python-2.7.13-fix-ssl-leak.patch
- config/software/python.rb
Fixes a regression in python `2.7.13` which causes a memory leak in the forwarder when SSL validation is enabled.
The memory leak was originally fixed in [[1]], but got re-introduced in https://github.com/python/cpython/commit/c2fc7c4f53069558b52d7a497fc195efebe8b4db#diff-e1cc5bf74055e388cda128367a814c8fR1104
The code snippet in [[1]] reproduces the mem leak on a vanilla `2.7.13` python.
More details on the 2 commits, which implement 2 different fixes. The last commit implements what I believe is a safer approach for us (since it basically reverts the problematic change).
I've tested both fixes against the current build of the agent and they both seem to work fine and fix the leak.
I'll submit the issue/patch upstream shortly
[1]:https://bugs.python.org/issue25569
> [python] Add patch to fix ssl module mem leak

- config/software/python.rb
Supersedes #125.
The mem leak of `2.7.13` can't be fixed on windows since we don't build from source, so we need to downgrade until `2.7.14` is released.
> [python][windows] Downgrade to python 2.7.12

- config/software/pyodbc.rb
Binary wheels are provided on Windows/MacOS but not on Linux
> [pyodbc] Add software definition

- config/software/net-snmp-lib.rb
- config/software/net-snmp.rb
Fixes the OSX build after breaking it with the addition of the snmp check and its dependent `net-snmp-lib`.
Reported here: https://github.com/DataDog/datadog-agent/issues/187
--------------------------------------------------
/cc @masci
> [net-snmp][net-snmp-lib] fix OSX build + ipv6 support

- config/software/psycopg2.rb
As omnibus health check doesn't detect they're there. They're all in
/opt/datadog-agent/embedded/lib/python2.7/site-packages/psycopg2/.libs
but it doesn't seem to be part of the path where omnibus looks for
dependencies, that's why we have to whitelist them (with a regex because
we can only have one 'whitelist_file').
> [psycopg2] whitelist all internal deps

- config/software/kafka-python.rb
Adds bugfixes and supports some new kafka protocol calls
See also https://github.com/DataDog/integrations-core/pull/272
> Bump kafka-python to 1.3.3

- config/software/boto.rb
AWS az "us-east-2" has been added in boto 2.43. We currently ship 2.39.
This bump boto to the latest version (2.46.1 right now)
> Bump boto version to 2.46.1

- config/software/datadog-gohai.rb
Fixes the build (see https://circleci.com/gh/DataDog/docker-dd-agent-build-deb-x64/1839 for example).
For some reason, when the deps of gohai are not yet present
in the gopath, `go get`ting gohai fails by getting the latest version
of gopsutil, which is only compatible with go >= 1.8.0. This happens
even with the `go get -d` option, which is supposed to only download
the packages.
As a workaround, we `go get` gohai only once the deps are already
present and pinned to supported versions.
The whole software def is quite ugly, that'll improve once we can
start using `glide` (which is blocked on the upgrade of go, which
itself waits on the upgrade of the centos build image to centos 6)
> [gohai] Fix build with old version of go (1.3)

- config/software/python-rrdtool.rb
Add `thrdvar.h` to x64 folder, required to build `python-rrdtool`
> [python-rrdtool] Add thrdvar.h to x64 folder

- config/software/libxml2.rb
Fix for CVE-2013-0339 and CVE-2014-3660
tested build process is fine, agent working fine 👍
> [libxml2] bumping default version to 2.9.4.

- config/software/python-rrdtool.rb
This reverts commit ca32d44999f3f04c1fdfb59942e053a0025d00c0.
Causes build to fail with centos 5
> Revert "[python-rrdtool] Add thrdvar.h to x64 folder (#139)"

- config/software/python-etcd.rb
Changelog audited and no breaking API changes for the methods we use
Dependency for https://github.com/DataDog/dd-agent/pull/3357
> bump python-etcd to 0.4.5 to get auth support

- config/software/cacerts.rb
The cacerts got a new release today, see https://curl.haxx.se/docs/caextract.html
This PR updated the checksum to that new release
> update cacert checksum to latest release

- .travis.yml
- config/software/jmxfetch.rb
Fixing cop issue with the `jmxfetch` definition - use `raise` rather than `fail`
> [jmxfetch] raise rather than fail - rubocop.

- config/software/datadog-upgrade-helper.rb
Go was inexplicably hard-coded to a certain location, which would (obviously) cause a failure if go is installed anywhere else.
> [windows] use the system go, in the path, rather than hard-coded

- config/software/datadog-upgrade-helper.rb
of external dependencies of the build
> [windows] use system 'move' rather than buildtools 'mv'.  Reduces number

- config/software/kazoo.rb
Pickup a number of bugfixes and minor improvements in the latest version of `kazoo`
Sister PR: https://github.com/DataDog/integrations-core/pull/623
> Bump Kazoo dependency to 2.4.0

- config/software/kafka-python.rb
Pickup some upstream bugfixes.
I'm one of the maintainers of `kafka-python`, so if there are any issues please file a bug and we'll try to get it fixed.
Sister PR: https://github.com/DataDog/integrations-core/pull/684
> Bump kafka-python to 1.3.4

- config/software/python-rrdtool.rb
Grabbing from `http://foo` was breaking the build due to the reditect - this pulls directly from `https` which is the right thing to do anyways.
> [rrdtool] avoid redirect, grab directly from https.

- config/patches/datadog-metro/libpcap-static-link.patch
Since https://github.com/google/gopacket/commit/895488bc9260b091df44a3937a15cef7b0aaae6a the patch doesn't apply cleanly. Fix this to unblock the 5.17.0 agent build.
At some point we should probably pin all these deps.
> [datadog-metro] Update pcap patch

- config/software/sysstat.rb
So although we probably want to enable support for `libsensors` into `sysstat`, we didn't provide this in the past. So let's disable it until we add the libsensors definition.
Note: it should've been straight-forward to fix, but I ran into some issues as libsensors appeared to depend on flex, and bison, and then I hit some unexpected error related to `yacc`. So until we figure that out, this probably makes sense.
> [sysstat] disable sensors - wasnt provided in the past.

- config/software/pycurl.rb
In older versions of windows, certutil returned the hash with each hex 8 bits separated by a space.  Newer versions (windows 10), perhaps server 2016, return the hash with out the spaces.
This version works on older and newer versions of windows.
> [windows] Fix pycurl hash check. Some (windows10) instances don't output

- config/software/jmxfetch.rb
Tested on both builds - works just fine.
> [jmx] handle both agent6 and agent5 definitions.

- config/software/supervisor.rb
Bumping supervisor to 3.3.3 to address known vulnerablity: [CVE-2017-11610](https://github.com/Supervisor/supervisor/issues/964)
> [supervisord] bumping to 3.3.3

- config/software/cacerts.rb
Builds are currently broken because of this.
I'll cherry-pick the commit to the `5.17.x` once the PR is merged to master.
> [cacerts] Update checksum to latest

- config/software/net-snmp-lib.rb
- config/software/net-snmp.rb
- config/software/zlib.rb
Avoid downloading source from sourceforge for 2 deps the `datadog-agent` omnibus build relies on:
* zlib: download from upstream
* net-snmp: download from our S3 bucket
SourceForge is too unreliable, avoid using it.
> Avoid sourceforge downloads

- config/software/cacerts.rb
The cacerts have been updated upstream, let's update the hash we check
against.
> [cacerts] Update hash to latest version

- config/software/cryptography.rb
- config/software/pyopenssl.rb
- config/software/unixodbc.rb
`unixodbc` is required by `SQLserver`. We were not currently shipping it although it is technically a linux-compatible integration. 
Also upgraded pyopenssl and cryptography to match integrations requirements, it was probably about time to upgrade both. I haven't encountered any issue in testing, but please let me know if anyone has any issues with that upgrade.
> [unixodbc] add software definition + pyopenssl/cryprograhy upgrade

- config/software/python-rrdtool.rb
Switch mirrors to avoid certificate error. I'm not sure if we'll want to move back to the swiss mirror in the future, but right now the build fails with a bad certificate problem.
> [rrdtool] change source to avoid cert issue

- config/software/jmxfetch.rb
Modify the permissions of JMXFetch jar from 0600 to 0644.
For some reason JMXFetch jar permissions were set to `0600`. On mac osx a standard install will result in all files in `/opt/datadog-agent` being owned by `root`. Under these conditions it was not possible for the agent to read the jar file. 
Fixes https://github.com/DataDog/dd-agent/issues/3512.
Agent6: https://github.com/DataDog/datadog-agent/pull/1170.
> Fix JMXFetch jar permissions

- config/software/py-compiled-cleanup.rb
> Add implementation of `py-compiled-cleanup` for windows, so we don't

- config/software/openssl.rb
Bumps openssl to a more current version.
OpenSSL is currently still maintaining the `1.0.x` branch, but `1.1.x` is out too. Maybe the next upgrade should contemplate a minor bump as well.
> [openssl] bumping openssl version to 1.0.2o

- config/patches/protobuf-py/setup-py-no-debug-symbols-for-gcc-41.patch
- config/software/protobuf-py.rb
Newer `protobuf` versions removed the old GCC (4.1) build issues, however I was still getting some issues building the wheel on RHEL, removing debug symbols allowed me to successfully complete the build. 
Unfortunately windows would require added work and we don't really need the C++ protobuf bindings on the platform, so we'll just continue shipping the pure-python variant there.
> [protobuf] static build + wheel, no bloat + RHEL support

- config/software/six.rb
Not aligned with `datadog-checks-base`. This is a temporary fix. The end-goal is to have a single source of truth, that will live in `integrations-core`. Very soon we'll be using the UCS4 wheels for protobuf-py, so we will not need to use this software definition, effectively solving the problem.
But let's bump anyways.
> [six] bumping version to 1.11.0

- config/software/datadog-gohai.rb
- config/software/datadog-metro.rb
Our builder is based on centos5. Building gometro with a recent version of go on it was deemed too much work. Instead we'll ship a prebuilt binary.
It was built in almost the same builder docker image with centos6 instead of centos5.
> ship prebuilt gometro on RHEL

- config/software/datadog-metro.rb
calling `source :sha256 => "a6fb05dcbe0f412eaac44095db67a8d71cce6c66dc900b0b78258de4ee43bf2f"` without also setting a source url was making omnibus throw an exception.
> fix error on debian builder

- config/software/datadog-metro.rb
After download go-metro might not be executable, make sure it is.
> [go-metro] make executable after copying over

- config/software/protobuf-py.rb
New url is `https://github.com/protocolbuffers/protobuf`
> update protobuf repo url

- config/software/docker-py.rb
Follow-up to https://github.com/DataDog/dd-agent-omnibus/pull/275, docker-py install is now failing.
Don't use --install-option to specify the scripts path, as this disables wheels, and one of the
docker-py deps (pywin32) can only be installed with a wheel. docker-py doesn't ship any scripts anyway.
> [docker-py] Remove `install-option` from docker-py pip install

- config/software/jmxfetch.rb
New JMXFetch release, also new location for the JARs, not all JARs are available in the new locations, so cleaned up the definition a little bit.
> [jmxfetch] bumping to 0.23.0 changing JAR source

- config/software/jmxfetch.rb
https://github.com/DataDog/jmxfetch/releases/tag/0.24.0 (feature is APM-only, but still let's use the build in the regular agent)
> [jmxfetch] Use 0.24.0

- config/software/python.rb
Running the omnibus recipes on arm currently will fail when compiling python with the following error:
```
/usr/bin/ld: /opt/datadog-agent/embedded/lib/libpython2.7.a(abstract.o): relocation R_ARM_THM_MOVW_ABS_NC against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/opt/datadog-agent/embedded/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
This PR adds `-fPIC` to the CFLAGS used to compile python.
> Compile python with -fPIC

- config/software/datadog-vsphere.rb
we can’t ship the latest version of the vsphere check in agent 5, because it now waits for the threads to finish running before returning from the check function, which might cause a problem if it takes too long.
> Add datadog-vsphere integration

- config/software/util-macros.rb
- config/software/xproto.rb
Requires https://github.com/DataDog/omnibus-ruby/pull/80
Rationale explained there, we want this for `xproto` because `http://cgit.freedesktop.org` is down ATM.
Tested on a gitlab pipeline: build passes, license files are in correct location
> [xproto] Ship license in source instead of downloading it separately

- config/software/python.rb
on development/build systems
Remove the setx command from the build definition.
It's not necessary, and it leaves an artifact; namely, it sets your PYTHON path to your embedded directory rather than the system path. All of our definitions explicitly call the python from the embedded directory, so it's not necessary
> remove setx from python def; it's not necessary and leaves bad artifacts

- config/software/datadog-agent-six.rb
Adds windows options to `datadog-agent-six`
Note that this definition doesn't put the DLLs anywhere useful (yet).  Mostly because we haven't decided where they should go (on windows).
Also note I changed the definition from a static tarball to `git:master`; needed up-to-date version to make it work on windows.
> Adds windows to `datadog-agent-six`

- config/software/pyyaml.rb
Bumps PyYaml to the latest 5.1.
Enable new `full_load()` option for customers perhaps wanting to use that after `load_all()` was patched for security reasons.
Cherry-pick to `agent-v5` branch.
Related PR: https://github.com/DataDog/dd-agent/pull/3839
> [pyyaml] bumping to 5.1

- config/software/cacerts.rb
- config/software/cacerts_py2.rb
- config/software/cacerts_py3.rb
Required by https://github.com/DataDog/omnibus-ruby/pull/82. See details there.
I checked these were the only software defs used by the Agent v6 build in `omnibus-software` that downloaded a single non-archive file using the `NetFetcher`.
> [cacerts] Use target_filename to define name of downloaded file

- config/software/datadog-pip.rb
Running the agent omnibus build raises the following error:
```
[Software: datadog-pip] I | 2018-10-17T23:09:02+00:00 | Building because `datadog-agent' dirtied the cache
[GitFetcher: datadog-pip] I | 2018-10-17T23:09:02+00:00 | Cleaning existing clone
[Builder: datadog-pip] I | 2018-10-17T23:09:02+00:00 | Starting build
[Builder: datadog-pip] I | 2018-10-17T23:09:02+00:00 | $ "/opt/datadog-agent/embedded/bin/pip" install --disable-pip-version-check --no-cache --upgrade /root/.omnibus/src/datadog-pip/p
ip/[tuf-in-toto]
[Builder: datadog-pip] I | 2018-10-17T23:10:11+00:00 | Execute: `"/opt/datadog-agent/embedded/bin/pip" install --disable-pip-version-check --no-cache --upgrade /root/.omnibus/src/datad
og-pip/pip/[tuf-in-toto]': 68.7528s
[Builder: datadog-pip] I | 2018-10-17T23:10:11+00:00 …
```
> Add libffi as dependency of datadog-pip on arm platforms

- config/software/autoconf.rb
- config/software/automake.rb
- config/software/libiconv.rb
- config/software/libsqlite3.rb
- config/software/libxslt.rb
- config/software/ncurses.rb
This PR fixes the following error that occurs when compiling various libraries on an arm64 box:
```
Error:
./config.guess: unable to guess system type
This script, last modified 2009-02-03, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
```
This built-in method is already in use in the …
> Update autoconf config information to support building on newer platforms

- config/software/libkrb5.rb
Health check found that `libkrad.so` was being linked against the system `libverto`. Kerberos prefers the system `libverto` if it is installed, otherwise it's built from sources. With this change it will always build it.
Docs for the `configure` option can be found here:
http://web.mit.edu/~kerberos/krb5-1.13/doc/build/options2configure.html
Found the problem when building on CentOS 7, which has `libverto` installed because `yum` depends on it.
> Fix krb5 linking against system libverto

- config/software/libyaml-windows.rb
- config/software/libyaml.rb
0.2.2 is the version that was released together with our current version of pyyaml, as per [1]
[1] https://pyyaml.org/
> Update libyaml to 0.2.2

- config/software/pkg-config.rb
- config/software/procps-ng.rb
- config/software/sysstat.rb
Following a change on how source shipping is done in the `omnibus-ruby` repo, the corresponding software definitions have been changed.
[This omnibus-ruby PR](https://github.com/DataDog/omnibus-ruby/pull/83) should be merged before this PR, as it implements the `ship_source` method change.
> [ship_source] Change software definitions for software using ship_source

- config/software/unixodbc.rb
Instead of trying to pull it from a remote website that may be
unavailable.
Also, simplify the software definition by using a relative_path instead
of copy-pasting the working directory to run commands from.
> [unixodbc] Ship license that's shipped with the source

- config/software/datadog-gohai.rb
Newer versions use type aliases but we're building with an older Go.
> datadog-gohai: pin the version of the dep golang.org/x/sys/windows/registry

- config/software/libffi.rb
If the `#{install_dir}/embedded/include` directory does not exist before (for example, because no dependency ever creates it), then the line:
```
copy "#{install_dir}/embedded/lib/libffi-#{version}/include/*", "#{install_dir}/embedded/include"
```
Takes every file in `#{install_dir}/embedded/lib/libffi-#{version}/include/*` one by one, and copy them in a file named `include` in `#{install_dir}/embedded`.
The end result is that we have one file named `include`, with the contents of the last file matched by `#{install_dir}/embedded/lib/libffi-#{version}/include/*`, while we wanted all files matched to be present in the `include` directory.
A software definition should generally not depend on behaviour that is not guaranteed by their dependencies (or by non-dependecies which usually run …
> [libffi] Fix include copy

- config/software/openssl.rb
Bump openssl to latest 1.0.2 version. Also, remove earlier versions with md5 hashsums.
1.0.2 will be EOL at the end of the year (Dec 31, 2019), so scheduling work to bump to the latest 1.1.1 release before then. According to the [python 2.7.17 release notes](https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.17rc1.rst) there are known issues with building python 2.7 < 2.7.17 against openssl 1.1.1, so I'll schedule this work at the same time as the upgrade to python 2.7.17.
Going to trigger a `datadog-agent` pipeline against this branch to make sure everything builds fine.
> Bump openssl to 1.0.2t

- config/software/python.rb
Bump Python version to 2.7.16
2 fixed CVEs are mentioned there: https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.17rc1.rst.
Check agent 5 with a custom build on Ubuntu and Windows: OK
> Update to Python 2.7.17

- config/software/cacerts.rb
- config/software/cacerts_py2.rb
- config/software/cacerts_py3.rb
The usual cacerts hashsum update.
Will need to be cherry-picked to the Agent 5 branch if we do an A5 release.
> Update cacerts hashsum (Nov. 2019 edition)

- config/software/unixodbc.rb
Upgrade unixodbc to 2.3.7 mainly address [CVE-2018-7409](https://access.redhat.com/security/cve/cve-2018-7409)
`unixodbc` change log: https://fossies.org/linux/unixODBC/ChangeLog
Use `http://www.unixodbc.org` instead of `https://downloads.sourceforge.net`. Reason: Source forge version of 2.3.7 is a `pre` version "unixODBC-2.3.7pre.tar.gz". The hash is different. Most sources suggest to download via `http://www.unixodbc.org`.
TLDR, works on docker agent & debian.
On AGENT 6.15.0~rc.1-1
```
$ strings /opt/datadog-agent/embedded/lib/libodbc.so.2 | grep '2.3'
GLIBC_2.3
$2.3.fA
2.3.4
```
On AGENT 7.17.0 custom build with unixodbc 2.3.7 installed
```
strings /opt/datadog-agent/embedded/lib/libodbc.so.2 | grep '2.3'
GLIBC_2.3
$2.3.fA
2.3.7
```
unixodbc 2.3.7 working fine with sqlserver See QA …
> Update unixodbc version to 2.3.7

- .travis.yml
Upgrades the ruby version used in travis to 2.3 (the version we use to build the Agent).
A recent omnibus-ruby refactor broke compatibility with EOL ruby 2.1, and it's better to use the ruby version that's actually used in the main Agent repo.
> [CI] Upgrade ruby version to 2.3

- config/software/autoconf.rb
- config/software/curl.rb
- config/software/procps-ng.rb
- Upgrading curl to 7.66.0
- Upgrading autoconf to 2.69
- Upgrading procps-ng to 3.3.16
> Upgrading procps-ng, autoconf and curl versions

- config/patches/openssl/openssl-1.1.1d-do-not-build-docs.patch
- config/software/cryptography.rb
- config/software/openssl.rb
- config/software/postgresql.rb
- config/software/pyopenssl.rb
We need to bump pyopenssl in order to be compatible with openssl 1.1.1.
> [A6] Bump openssl to 1.1.1 and pyopenssl to 19.0.0

- config/software/libsqlite3.rb
For CVE-2019-5018 and CVE-2019-19603
I don't really know why we were not relying on official sqlite repository, but I don't really know if there is another valid location with the latest source code.
> Bump sqlite version from 3.7.7.1 to 3.31.1

- config/software/openssl.rb
A request for 1.1.1d results in a 404 and is no longer available. This causes compilation of datadog-agent to fail from Linux. Compilation is successful with 1.1.1f.
> Bump openssl-1.1.1d to 1.1.1f

- config/software/openssl.rb
Adds a comment on the openssl software definition explaining the recent changes made by openssl.org regarding their way of making old sources available.
> [openssl] Explain source URL changes

- config/software/cacerts.rb
- config/software/cacerts_py2.rb
- config/software/cacerts_py3.rb
Following the 2020/06/24 bundle update: https://curl.haxx.se/docs/caextract.html
> [cacerts] Update hashsum

- config/software/cacerts.rb
Following the 2020-07-22 bundle update: https://curl.haxx.se/docs/caextract.html
> [cacerts] Update cacert hash

- config/software/cacerts.rb
Following the 2020-07-22 bundle update: https://curl.haxx.se/docs/caextract.html
> [cacerts] Update cacerts hash

- config/software/openssl.rb
Motivation: none in particular, simply noticed that we weren't shipping the latest `1.1.1` version. Let' ship it for 7.25.
Also updated the comment (the link doesn't necessarily seem to break on every openssl release, it didn't this time typically).
A `datadog-agent` gitlab pipeline using this branch works (see pipeline id `3469469`). The `build-system-probe-arm64` fails but seems to fail on master as well at the moment, so very likely not related to this change.
> [openssl] Bump to 1.1.1h

- config/software/openssl.rb
Bump to latest OpenSSL for milestone 7.25.0
Pipeline `3505714` has a successful run with this commit.
> openssl: bump to 1.1.1i

- config/software/cacerts.rb
Updates cacerts hash to match the latest cacerts.
> [cacerts] Update hash (2021-04-13)

- config/software/cacerts.rb
Pins a specific version of cacerts instead of the latest one.
Avoid breaking all Agent builds when the cacerts bundle changes. We now have a monitor to alert us instead.
> [cacerts] Pin bundle version

- Gemfile
- config/software/jmxfetch.rb
Since bintray is sutting down, this change ensures that we get our
artifacts from Sonatype instead.
Note: Since artifacts for Agent 5 were not on Sonatype previously, a
manual publish was done but for those specific versions the filename
was mangled by Sonatype so there are overrides for the URL endpoint to
ensure that we are retrieving the proper file.
> [jmxfetch] Move bintray enpdoints to Sonatype for Agent v5

- config/software/datadog-gohai.rb
The `go get -u` pattern was causing build issues, we can just get, and then `git checkout` to the correct tag.
> [gohai] manually get correct tag, don't go get -u

- config/software/unixodbc.rb
Removes empty example files that unixodbc places in the embedded directory. On upgrade, these empty files would replace any configuration set by the user.
Adds a section in the `embedded/etc/README.md` file about unixodbc config files.
> [unixodbc] Delete empty example files

- config/software/cacerts.rb
Add one explanation to why we need to ship cacerts in the datadog-agent package, so that we have an answer ready the next time we ask ourselves why we're shipping them.
There may be other cases where they're needed, they'll be added here when we find them.
> Add note about why we ship cacerts

- config/software/libyaml.rb
Fix license file location: https://raw.githubusercontent.com/yaml/libyaml/master/LICENSE leads to a 404 page.
> [libyaml] Fix license file location

- config/software/procps-ng.rb
https://gitlab.com/procps-ng/procps/raw/master/COPYING.lib leads to a 404 page. The correct page is https://gitlab.com/procps-ng/procps/raw/master/COPYING.LIB.
> Fix procps-ng path

- config/software/cryptography.rb
- config/software/libffi.rb
- config/software/libiconv.rb
- config/software/liblzma.rb
- config/software/libtool.rb
- config/software/libyaml.rb
- config/software/makedepend.rb
- config/software/nghttp2.rb
- config/software/pkg-config.rb
- config/software/psutil.rb
- config/software/pyyaml.rb
- config/software/util-macros.rb
- config/software/xproto.rb
Use sha256 checksums in software definitions used by the Agent.
Omnibus won't accept md5 nor sha1 anymore after we merge https://github.com/DataDog/omnibus-ruby/pull/136
Some definitions we don't use still have md5 and sha1 hashes, but that's
fine because if we ever try to use them as-is, omnibus will raise an error.
> Remove usage of md5 for checksums in Agent dependencies

- config/software/libedit.rb
- config/software/libxslt.rb
- config/software/postgresql.rb
Follow-up of #412, this time for dependencies that are used in ARM builds of the Agent.
> Remove usage of md5 checksums for ARM Agent dependencies

- config/software/openssl.rb
Bump OpenSSL to 1.1.1n following the recommendations of https://www.openssl.org/news/secadv/20220315.txt.
> [openssl] Bump to 1.1.1n

- config/software/openssl.rb
Backport of #415.
Bump OpenSSL to 1.1.1n following the recommendations of https://www.openssl.org/news/secadv/20220315.txt.
> [backport] [openssl] Bump to 1.1.1n

- config/software/libtool.rb
- config/software/openssl.rb
- config/software/unixodbc.rb
Tries to update a few software definitions that are not using multiple jobs.
For `libtool`, the `-j #{workers}` option was removed in https://github.com/DataDog/omnibus-software/pull/101, but the reason wasn't explained, and there doesn't seem to be a particular reason not to use the option.
For `unixODBC`, the `-j #{workers}` was never set: https://github.com/DataDog/omnibus-software/pull/176, but I haven't been able to find a reason why that wouldn't work.
For `openssl`, the `-j #{workers}` option was removed in https://github.com/chef/omnibus-software/pull/91 because of race condition issues during `make`, but that was on `openssl 1.0.1e`, which is 8+ years old (we currently use `1.1.1n`).
This shaves a few minutes off `datadog-agent` omnibus builds.
Test pipeline: …
> Use -j make option in software definitions that don't use it

- config/software/cacerts.rb
Updates cacerts to the latest available version.
Test pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/7480656
> [cacerts] 2022-03-29 update

- config/software/zlib.rb
`zlib` has been updated for the first time in 5 years, [see changelog](https://zlib.net/ChangeLog.txt).
This PR updates the `zlib` version used in the datadog-agent project, as well as the download link used to download sources (`https://zlib.net/zlib-#{version}.tar.gz` only works for the latest `zlib` version).
Alternatively, we can keep using `1.2.11`, but we'll have to change the download link anyways.
> [zlib] Bump to 1.2.12

- config/software/cacerts.rb
So that we can still build omnibus-builds on our 7.35.x branches
> [cacerts] 2022-04-26 update

- config/software/openssl.rb
> [backport] Upgrade OpenSSL to 1.1.1o (fix CVE-2022-1292)

- config/patches/openssl/openssl-1.1.1q-include-string.patch
- config/software/openssl.rb
- config/software/unixodbc.rb
Makes the Datadog Agent buildable on the macOS 11 Github Actions runners. In particular:
- Applies patch to OpenSSL to address openssl/openssl/issues/18720
- Bumps unixODBC version to address https://trac.macports.org/ticket/61460
> Fix macOS 11 build

- config/software/cacerts.rb
- config/software/datadog-gohai.rb
- config/software/nfsiostat.rb
- config/software/zlib.rb
- zlib: bump to 1.2.13; previous versions unavailable (+ vulnerable)
- nfsiostat: new git repository
- gohai: change order in which deps are collected, checked out.
> [agent-v5] updates to fix current build

- config/software/cacerts.rb
This is backport of #435 in `7.42.x` for possible `7.42.1` releases !
> Backport cacerts 2023-01-10 update

- config/software/ncurses.rb
Bump ncurses dependency with fix to vulnerability to CVE-2023-29491.
ncurses latest official release is 6.4 20221231. Since then Thomas E. Dickey <dickey@invisible-island.net> took on maintenance and releases patches on https://invisible-island.net/
> [ncurses] bump to 6.4-20230527

- config/software/ncurses.rb
Backport of #453.
Bump ncurses dependency with fix to vulnerability [CVE-2023-29491](https://github.com/advisories/GHSA-vh2x-5rx6-qqhv)
`ncurses` latest official release is 6.4 20221231. Since then Thomas E. Dickey [dickey@invisible-island.net](mailto:dickey@invisible-island.net) took on maintenance and releases patches on https://invisible-island.net/.
> [backport] [ncurses] bump to 6.4

- config/software/openssl.rb
Fixes CVE-2023-2650, CVE-2023-0466, CVE-2023-0465 and CVE-2023-0464.
See https://www.openssl.org/news/openssl-1.1.1-notes.html for more details
> [openssl] Upgrade to 1.1.1u

- config/software/zlib.rb
For the fips-proxy, we would like to bump up zlib to the newest version 1.3, released on August 18, 2023. Since fips-proxy does not directly specify its own zlib version but instead uses the zlib in omnibus, this means bumping the version here. Although this has the side effect of changing the zlib version for all that depend on omnibus, this is probably a benefit. We hope that any issues this might cause will be caught in the nightly CIs.
> Bump zlib version to 1.3

- config/software/config_guess.rb
Not doing so will prevent omnibus from caching the resulting files, which later causes build failures as config.guess is nowhere to be found
> config.guess: install files in {install_dir}

- config/software/openssl3.rb
(cherry picked from commit ae78827ec7731a1142b9be4c89cf529b758e81f2)
Signed-off-by: Hugo Beauzée-Luyssen <hugo.beauzee@datadoghq.com>
> openssl: bump default version to 3.0.11

- config/software/bzip2.rb
- config/software/libffi.rb
- config/software/liblzma.rb
- config/software/libtool.rb
- config/software/nghttp2.rb
- config/software/openssl.rb
- config/software/openssl3.rb
- config/software/postgresql.rb
- config/software/procps-ng.rb
- config/software/zlib.rb
This PR disables static libraries generation, or removes those files when the build system doesn't allow for disabling.
It also removes i18n support from a few softwares.
The intent is to reduce the size of our artifacts, and since we don't need the shared libraries to be shipped, might as well remove them. Static libraries account for ≃25MB in the debian package (I haven't checked the footprint for other platforms/distributions)
> Remove static libraries from install directory

- config/software/curl.rb
backport of #478 to 7.48.x branch
> Update curl to latest version

- config/software/postgresql.rb
Only pg_config is required later on.
Tested with a pipeline with all tests here: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/21687272
> postgres: remove most binaries [APL-2361]

- config/software/postgresql.rb
Bumps postgres dep to the [latest verison](https://www.postgresql.org/docs/release/16.0/), which we can support now that we have merged a change to deploy [the latest version](https://github.com/DataDog/integrations-core/pull/15949) of `psycopg2`, which ships with the latest version of `libpq` & that supports postgres 16. 
This fixes some [reported CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-336/product_id-575/version_id-1354580/Postgresql-Postgresql-10.19.html) for postgresql 10 (its a very old version)
> Bump postgresql dep to latest version

- config/software/openssl3.rb
> openssl3: update to 3.0.12

- config/software/datadog-agent-six.rb
Use the upstreamed `cmake` function instead of a homemade equivalent
This allows to centralize our cmake invocations, which will simplify selecting a different toolchain & similar tweaks
Tested with this pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/22116693
> Use upstream cmake function

- config/software/libsqlite3.rb
This PR is updating sqlite3 to the version we were already building in the datadog-agent repo (3.43.1) and updated a few things in the recipe.
> update sqlite to 3.43.1

- .gitlab-ci.yml
We are currently excluding stable branches, but not the tags associated with them, which causes a pipeline to be created while we already tested the build with the commits it contains
> CI: don't trigger a datadog-agent pipeline on tags

- config/software/nghttp2.rb
Upgrade `nghttp2` to `1.58.0` to get the fix for [CVE-2023-35945](https://nvd.nist.gov/vuln/detail/CVE-2023-35945).
> [VULNOPS-1127] Upgrade nghttp2

- config/software/curl.rb
- config/software/expat.rb
- config/software/libarchive.rb
- config/software/libiconv.rb
- config/software/libpcap.rb
- config/software/libsqlite3.rb
- config/software/libyaml.rb
- config/software/makedepend.rb
- config/software/ncurses.rb
- config/software/nghttp2.rb
- config/software/postgresql.rb
- config/software/procps-ng.rb
- config/software/xproto.rb
- config/software/zlib.rb
The intent is to use the same wrappers as much as possible, in order to have a single place to update to change the way we use autotools and cmake.
This change makes it easier to switch to a custom toolchain, by only changing the 2 wrappers, instead of sprinkling environment variable throughout all our recipes
> Use our existing wrappers for cmake & configure

- config/software/zlib.rb
Bump Zlib to the latest version. We (ASC) need it for the FIPS Proxy
> Bump Zlib version to 1.3.1

- .github/workflows/open-datadog-agent-pr.yml
Removed the milestone computing & setting in the `open-datadog-agent-pr.yml` since [it's now automatically assigned](https://github.com/DataDog/datadog-agent/blob/1a7803ec982ea73f96369c9d76f5f8f8c04300ad/.github/workflows/add_milestone.yml).
> [CI] No need for milestone anymore in datadog-agent's PR

- .gitlab-ci.yml
The `rules` mark the job as always ran, which defeats the purpose of the `on_success` `when` clause for the `on_success` job.
> CI: fix job rules to avoid running on_success job in case of failure

- .github/workflows/open-datadog-agent-pr.yml
`qa/skip-qa` -> `qa/no-code-change` in the auto pr creation in the datadog-agent repo.
> [CI] Deprecate qa/skip-qa label

- config/software/libxml2.rb
Fix [VULNOPS-1340](https://datadoghq.atlassian.net/browse/VULNOPS-1340?atlOrigin=eyJpIjoiODk5NzU4YThlZTg2NDlhMTkzZjliOGFiYjkwYjI2YmIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ).
See https://github.com/DataDog/integrations-core/pull/17432 for reference. In future releases this dependency will probably not be taken from this Omnibus definition but built into a Python dependency on integrations-core.
[VULNOPS-1340]: https://datadoghq.atlassian.net/browse/VULNOPS-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump libxml2

- config/software/libxml2.rb
The original change (#519 ) contained fatal mistakes.
Acts as a backport for #520.
> Fixing errors with libxml bump

- config/software/unixodbc.rb
As far as I understand, we no longer need to ship postgresql explicitly with the Agent after https://github.com/DataDog/datadog-agent/pull/23094, as we're now building it and bundling it as necessary with integration dependencies.
> Drop postgresql as a dependency for unixodbc

- config/software/libffi.rb
We seem to sometimes have errors when fetching from FTP: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/536079168
> libffi: use an HTTPS mirror

- config/software/openssl3.rb
Mostly aiming at fixing `CVE-2024-4741`
> openssl: bump to 3.0.14

- config/software/cacerts.rb
A new file exist upstream and the hash needs to be updated.
> Update cacert.pem file's hash

- config/software/curl.rb
* curl: update from 8.4.0 to 8.7.1
* curl: remove old and unneeded workaround
(cherry picked from commit 6837021672ce6ffd753cb6cb284b2f95a799e900)
> Update cURL to 8.7.1 (#535)

- .github/workflows/no-auto-bump.yml
- .github/workflows/open-datadog-agent-pr.yml
Github token permissions should follow the least privilege principle
Reset workflow permissions to validate we can enable read-only default permissions at repository level to provide a strong baseline protection measure
> chore(github): reduce workflow token permission

- config/software/openssl.rb
- config/software/openssl3.rb
This is a build tool that can be installed in the build image directly, but as it turns out, it just isn't required :shrug:
> openssl: drop makedepend dependency

- config/patches/bzip2/soname_install_dir.patch
- config/software/bzip2.rb
- config/software/ncurses.rb
- config/templates/bzip2/bzip2.pc.erb
[BARX-563](https://datadoghq.atlassian.net/browse/BARX-563)
This makes the build of Python 3.12 work on macOS (https://github.com/DataDog/datadog-agent-macos-build/actions/runs/10826570028/job/30037807223).
I'll probably have a more complete write-up of it elsewhere at some point, but I'll try to summarize things here.
The crux of the matter is that Python 3.12 introduced significant changes in their build system (notably incorporating the use of pkgconfig in module detection) which broke some things on our build.
- ncurses:
- IIUC The Python build now assumes that on macOS, if ncurses is found, it must be with wide char support (without checking further). As it turns out, we were building both a wide and a non-wide version of ncurses, but the non-wide version's header overwrote the …
> Fix Python build dependencies

- config/software/curl.rb
This fix a potential issue (most likely only in more recent toolchains
than the one we use in the build images) where curl would explicitly
depend on the absolute path to its dependencies, causing it to link with
/path/to/libfoo.so instead of -lfoo
When linking with an absolute path, the linker appears to not include
the rpath information, which causes linking errors down the line:
```
2023-10-25T15:16:09+00:00 | /opt/toolchains/bin/../lib/gcc/x86_64-unknown-linux-gnu/11.4.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: warning: libnghttp2.so.14, needed by
../lib/.libs/libcurl.so, not found (try using -rpath or -rpath-link)
```
> curl: don't hardcode path to dependencies

- config/software/openssl3.rb
[BARX-558]
[BARX-558]: https://datadoghq.atlassian.net/browse/BARX-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> openssl: update to 3.3.2

- config/software/openssl3.rb
[BARX-558]
[BARX-558]: https://datadoghq.atlassian.net/browse/BARX-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> openssl: update to 3.3.2 (#544)

- config/software/cacerts.rb
This drops python2 support, and mostly drops the dependency on `with_python_runtime?` helper that is defined in the `datadog-agent` repo, and shouldn't be used from here
> cacert: drop python2 support

- config/software/curl.rb
- config/software/postgresql.rb
This is causing OpenSSL 1 to be used since the introduction of https://github.com/DataDog/datadog-agent/pull/30983
> drop OMNIBUS_OPENSSL_SOFTWARE environment variable

- config/software/openssl3.rb
Python build system expects this file to be present, so we want to install it
> openssl: explicitely install applink.c since python needs it

- config/software/openssl3.rb
Switch to the usual `configure` function which will provide the correct prefix on windows (and also just because it centralizes configure invocations)
This will install OpenSSL in the expected location on Windows
> openssl: use configure function instead of manual command

- config/software/libarchive.rb
> libarchive: don't build static library

- config/software/procps-ng.rb
> procps-ng: only ship the source offer

- config/software/ncurses.rb
We only need the lib, and I doubt we really need the term database since I don't expect the agent to ever wait for user input or display fancy ncurses interfaces
> ncurses: don't build programs nor term DB

- .gitlab-ci.yml
Avoid surprising results such as https://gitlab.ddbuild.io/DataDog/omnibus-software/-/pipelines/54026398 where only a patch changes.
> CI: run a downstream pipeline in case a patch gets updated

- .github/dependabot.yaml
- .github/workflows/no-auto-bump.yml
- .github/workflows/open-datadog-agent-pr.yml
- config/software/openssl3.rb
- Pin github actions
- Enable dependabot
And the repository settings where updated to allow only a list of actions
> feat(security): Pin github actions

- config/software/curl.rb
Bump curl version to address CVE
> Update `curl` version to 8.12.1
